1464 Improve English Translations
marienfressinaud/FreshRSS pull request #1465
Opened 2017-03-21 16:49 UTC by jlefler

This pull request has no functional changes. It merely updates the English translation with minor changes to word choice and grammar to improve the user experience for English-speaking users. The incorrect translation that prompted the change was 'Actualise' when performing a feed update. I have replaced that with "Updating" and made other similar changes. Fixes #1464.

2017-03-21 21:19 UTC, Alwaysin requested changes

2017-03-21 21:19 UTC, Alwaysin commented on app/i18n/en/conf.php
> +		'auto_share_help' => 'If there is only one sharing mode, it is used. Other modes are accessible by their number.',
I think that "else" was used as in "otherwise" here - not "other", which would make more sense.

2017-03-21 21:26 UTC, jlefler commented
I'm fine with otherwise rather than other here.

On Tue, Mar 21, 2017, 16:19 Alwaysin <notifications@github.com> wrote:

> *@Alwaysin* requested changes on this pull request.
> ------------------------------
>
> In app/i18n/en/conf.php
> <https://github.com/FreshRSS/FreshRSS/pull/1465#discussion_r107278195>:
>
> > @@ -142,7 +142,7 @@
>  		'_' => 'Shortcuts',
>  		'article_action' => 'Article actions',
>  		'auto_share' => 'Share',
> -		'auto_share_help' => 'If there is only one sharing mode, it is used. Else modes are accessible by their number.',
> +		'auto_share_help' => 'If there is only one sharing mode, it is used. Other modes are accessible by their number.',
>
> I think that "else" was used as in "otherwise" here - not "other", which
> would make more sense.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreshRSS/FreshRSS/pull/1465#pullrequestreview-28241095>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACFTreZ2ntx7DsPkxNyjyCx48fuYwlMKks5roD7sgaJpZM4MkGHC>
> .
>

2017-03-22 09:50 UTC, aledeg commented on app/i18n/en/admin.php
> +		'status_favorites' => 'Favorites',
Both are correct. One is for US, the other one is for UK. I have no preference even though I am more used to "Favourites"

2017-03-22 09:53 UTC, aledeg commented
Look good to me.

@jlefler thanks

2017-03-26 17:34 UTC, merged

2017-03-26 17:34 UTC, Alkarex commented
Merged. Thanks again!

2017-04-01 10:00 UTC, Alkarex commented on app/i18n/en/gen.php
> +		'actualize' => 'Updating',
I think this one is wrong:
![image](https://cloud.githubusercontent.com/assets/1008324/24577685/c8e653c6-16d2-11e7-8e7d-1a99113994ce.png)
Should be something like *Actualize* or *Update*

2017-04-08 17:49 UTC, Alkarex commented on app/i18n/en/gen.php
> +		'actualize' => 'Updating',
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1492

2017-05-27 10:22 UTC, Frenzie commented
I would also change the "damn!" in error messages to something slightly more proper even if it's only a stylistic issue.

2017-06-03 13:09 UTC, Alkarex commented
https://github.com/FreshRSS/FreshRSS/pull/1561