Selinux FAQ
marienfressinaud/FreshRSS pull request #1837
Opened 2018-03-18 09:08 UTC by renzo38

Command to run on SELinux system enabled

2018-03-18 09:33 UTC, aledeg requested changes
I think there is typo. Anyway, thank you for your contribution.

2018-03-18 09:33 UTC, aledeg commented on docs/en/users/07_Frequently_Asked_Questions.md
> +semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data
I guess it's missing a quote at the end of the line. Same goes in the other file

2018-03-18 10:27 UTC, renzo38 commented
I added the missing quotes

2018-03-18 10:32 UTC, Alkarex commented
https://github.com/FreshRSS/FreshRSS/issues/1835#issuecomment-373907931

2018-03-18 10:32 UTC, aledeg commented
At first, I didn't see that the quotes you've corrected where missing :). Good catch. I was talking at the end of the line I've pointed. I should have:
```
semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data'
```
instead of 
```
semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data
```
Same goes in both files.

2018-03-18 11:50 UTC, aledeg approved these changes

2018-03-18 11:52 UTC, Alkarex commented
Copy from https://github.com/FreshRSS/FreshRSS/issues/1835#issuecomment-373987380

> The whole `./data/` should be writeable. For instance, `./data/PubSubHubbub/` was forgotten.

Hence the following suggestion:
```sh
semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data(/.*)?'
restorecon -Rv /usr/share/FreshRSS/data
```

2018-03-18 12:29 UTC, Alkarex commented
@renzo38 Did you maybe close this issue by mistake? :-)

2018-03-18 12:33 UTC, renzo38 commented
I closed this by mistake, sorry, doing several things together lead to this, sorry...

2018-04-25 19:38 UTC, Alkarex commented
@renzo38 Did you have a change to consider my suggestion, a bit higher up?
https://github.com/FreshRSS/FreshRSS/pull/1837#issuecomment-373992230

2018-04-26 05:36 UTC, renzo38 commented
So, I will modify the command to set the rights on the whole data sub-dirs.

2018-04-26 05:49 UTC, Alkarex commented
@renzo38 Is there a reason why you do not like my one-line suggestion https://github.com/FreshRSS/FreshRSS/pull/1837#issuecomment-373992230 ?
Everything under `./data/` is supposed to be writeable, otherwise it is not located there.

2018-04-26 06:05 UTC, renzo38 commented
No, no it's ok, I added the line at the end of the Readme, I can remove the previous lines, no problem.

2018-04-26 06:40 UTC, merged