extend hooks
marienfressinaud/FreshRSS pull request #2704
Opened 2019-12-06 08:43 UTC by cn-tools

I added two new hooks to have more options for influencing with extensions.

2019-12-06 08:48 UTC, aledeg commented
Thank you for your contribution.
Could you explain what are the use case for those new hooks? I guess that if you add those, you want new features for your extensions.

2019-12-06 09:25 UTC, cn-tools commented
Dear @aledeg !
I develop a new extension who should change the url in the add process. My idea is to change a YouTube Channel URL into an YouTube RSS Feed URL. (hook->'check_url_before_add')

The hook 'feed_before_actualize' is only a abstract idea :)

Have a look:
https://github.com/cn-tools/cntools_FreshRssExtensions

2019-12-06 11:06 UTC, aledeg requested changes
Apart from minor changes, this looks good to me.

2019-12-06 11:06 UTC, aledeg commented on lib/Minz/ExtensionManager.php
> +		),
Move that definition above to keep the list ordered.

2019-12-06 11:06 UTC, aledeg commented on lib/Minz/ExtensionManager.php
> +		),
Same here

2019-12-06 11:06 UTC, aledeg commented on app/Controllers/feedController.php
> +			if ($feed === null) {
Use `null === $feed` instead

2019-12-06 11:06 UTC, aledeg commented on app/Controllers/feedController.php
> +		if ($url === null) {
Use `null === $feed` instead

2019-12-06 12:10 UTC, cn-tools commented
thx 4 comments
change typography ... done

2019-12-06 13:16 UTC, aledeg approved these changes

2019-12-07 11:59 UTC, merged

2020-02-29 14:28 UTC, Alkarex commented
@Frenzie I am not up to date on how to change the documentation now; we should add the new hooks to the documentation in https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/developers/03_Backend/05_Extensions.md#the-hooks-system

2020-02-29 15:28 UTC, Frenzie commented
@Alkarex The English docs are the source, then there's a little helper script to generate the rest. Unfortunately you need po4a 0.56 which may not be readily available yet. That's just these two? I can submit a PR with that.

2020-02-29 15:41 UTC, Alkarex commented
Yes please @Frenzie 👍