Update doc about default configuration
marienfressinaud/FreshRSS pull request #3124
Opened 2020-07-22 12:29 UTC by LucasVerneyDGE

See https://github.com/FreshRSS/FreshRSS/issues/3066

2020-07-22 12:32 UTC, aledeg approved these changes

2020-07-22 13:14 UTC, Frenzie requested changes
Please also add it to the French one to keep it in sync.

Something like this but that's for @aledeg to judge. (In English is fine too; that's a to-be-translated.)
`Vous pouvez ensuite personnaliser [la configuration de votre instance](https://github.com/FreshRSS/FreshRSS/blob/master/config.default.php#L3-L4), [la configuration par défaut pour les nouveaux utilisateurs](https://github.com/FreshRSS/FreshRSS/blob/master/config-user.default.php#L3-L5) ou [l'ensemble des flux par défaut pour les nouveaux utilisateurs](https://github.com/FreshRSS/FreshRSS/blob/master/opml.default.xml#L2-L5).`

2020-07-22 13:43 UTC, LucasVerneyDGE commented
There is no "administrators" documentation in French https://github.com/FreshRSS/FreshRSS/tree/master/docs/fr.

2020-07-22 14:07 UTC, Frenzie approved these changes
My bad.

2020-07-23 09:26 UTC, merged

2020-07-23 09:27 UTC, Alkarex commented
Merci @LucasVerneyDGE 👍 
Pourriez-vous ajouter une ligne pour vous dans https://github.com/FreshRSS/FreshRSS/blob/master/CREDITS.md ?