Fixing user query searches
marienfressinaud/FreshRSS pull request #3214
Opened 2020-10-07 14:18 UTC by knasdk

Selecting user queries in drop down, now executes search.

Changes proposed in this pull request:

- Changed href when seleced user query

How to test the feature manually:

1. Select user query and the user query is used as a search parameter

Pull request checklist:

- [ ] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

2020-10-07 14:54 UTC, Alkarex commented
Hum, I think I understand what you want to achieve, but that would break existing user queries.
The name of the query is not meant to be searched, just to be a display name:

![image](https://user-images.githubusercontent.com/1008324/95347735-83eb2900-08bd-11eb-8d0a-21dccd7cec5f.png)

What you could do instead, is expose another field to edit the query.
Maybe @aledeg , who did this part, could have some more feedback

2020-10-07 14:55 UTC, Alkarex requested changes
The name of the query is not meant to be used for searching

2020-10-07 15:03 UTC, knasdk commented
@Alkarex, thanks for your comment.
I was afraid I'd missed the intent of user query usage - so I appreciate your patience!
I don't seem to be able to figure out how user queries are ment to be used, as is. Have I missed finding the documentation maybe?
Thanks!

2020-10-07 15:27 UTC, closed without merging

2020-10-07 15:29 UTC, Alkarex commented
You can save your searches from the main view like so:

![image](https://user-images.githubusercontent.com/1008324/95352562-a29fee80-08c2-11eb-940e-09c5d50d6610.png)

2020-10-07 15:32 UTC, knasdk commented
I know. When I select the ones I've created, the browser just reloads and nothing happens...

2020-10-08 17:25 UTC, Alkarex commented
@knasdk Could you please post a screenshot / screencast?
What link / address do your user queries contain?
Do you have any error in your browser console and/or in your Web server logs?

2020-10-09 14:21 UTC, knasdk commented
@Alkarex - thanks for asking.

When I from the selectbox choose a query, the href is `./`, and a GET request is send to `/i/`- it's like the page is just reloading.
The dom element is this:
```
<li class="item query">
    <a href="./">!#sport AND !#fodbold AND !#Kevin%sMagnussen AND !#Tennis</a>
</li>
```
There's no errors in the console, only `FreshRSS main init done.` from `main.js` line 1594.

I am hosting on an nginx server, and the root folder is `FreshRSS/p`

2020-10-09 20:30 UTC, Alkarex commented
@knasdk Right. The process is that you first search in FreshRSS, and you save this search as a user query. What you have done is that you have the search query in the name, and nothing in the search query itself.
Try again as in this screenshot:
![image](https://user-images.githubusercontent.com/1008324/95628684-d3c51e00-0a7e-11eb-8dde-7a4598c12af3.png)

By the way, you are welcome to send a PR to show and edit the queries in the user query management page.
Right now, we can only see and edit the name. There should be one more field to show and edit a search query itself.

2020-10-10 07:21 UTC, knasdk commented
@Alkarex, do you know the idea with query url and search - what's the difference?
The query link in the navigation, is using url as href, but the search parameter gets urldecoded in the controller.
It seems like search is ment to be used for search - but what is the idea with the url parameter?

2020-10-10 09:57 UTC, Alkarex commented
I have not written this part (@aledeg did) but URL is the actual query to be executed (that is the important part), while Search is used for the user interface (less important, cosmetic), to help telling what the query is doing (used together with State, Order, Get...).

2020-10-10 18:11 UTC, knasdk commented
@Alkarex, the changes I did so far, was via the web editor, but I would like to be able to push from the command line.
I do not have permission to FreshRSS/FreshRSS.git
How do people normally do this?

2020-10-10 19:14 UTC, Alkarex commented
@knasdk You start by forking the whole project into your own user space (top right in the Web interface). Then you make a new branch, in which you can commit your changes. Then from the Web interface you submit a pull request back to us. And it is possible to continue commiting more changes to your branch until the PR is merged. I am sure you can find a more detailed guide online.

2020-10-10 19:42 UTC, knasdk commented
@Alkarex - Thank you so much... I've just discovered what fork is - never done it before :+1: 
Now - are you OK with me deleting this PR?

2020-10-10 20:01 UTC, Alkarex commented
This PR is already closed. What you can do is delete is your own branch, which is only for housekeeping on your side and has no impact on the main FreshRSS repository :-)