Add an option to set a custom user agent to retrieve individual feeds
marienfressinaud/FreshRSS pull request #3494
Opened 2021-03-03 06:05 UTC by Jules-Bertholet

This allows retrieving the original RSS feed when websites use services like FeedBurner.

Closes #3493 

Changes proposed in this pull request:

- Add a setting to choose the user agent used when fetching feeds

How to test the feature manually:

1. Add a feed that is fronted by FeedBurner to FreshRSS. One such is `https://www.themoneyillusion.com/feed/atom`
2. Set the user agent to `FeedBurner`
3. Ensure the feed location still points to `https://www.themoneyillusion.com/feed/atom`, and was not changed to the FeedBurner feed because of a 3XX redirect before you added the user-agent
4. Re-fetch feed content
5. All feed items should now refer to the original site, not `feedproxy.google.com` or similar

Pull request checklist:

- [x] clear commit messages
- [x] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/master/docs/en/developers/04_Pull_requests.md).

2021-03-03 09:19 UTC, Alkarex commented on app/i18n/en/sub.php
> +		'useragent_help' => 'Example: <kbd>FeedBurner</kbd>',
Please use another example, avoiding specific product names, but a more general browser, e.g.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0)
```

2021-03-03 09:22 UTC, Alkarex commented
Please add a line for your new string in `./cli/i18n/ignore/en-us.php` to ignore the fact that it is the same string in en-GB and en-US

2021-03-03 12:19 UTC, aledeg requested changes
Could you add the translating strings from en_US in the ignore file?
Run this command to do that: `make i18n-ignore-unmodified-keys lang=en-us`

*Edit* This will fix the CI error!

2021-03-03 12:19 UTC, aledeg commented on app/Controllers/subscriptionController.php
> +			if ($useragent != '') {
Please, use `!==` instead of `!=`.

2021-03-03 12:22 UTC, aledeg commented on app/Controllers/subscriptionController.php
> +			if ($useragent != '') {
I know that the code around does not use it, but I think it should. We will fix it when working on it.

2021-03-03 15:56 UTC, aledeg approved these changes

2021-03-03 22:19 UTC, Alkarex commented
Works fine. But maybe this option should be made available from the *Add feed* page (`?c=subscription&a=add`).

Furthermore, we should either only allow those options for admins, or make them use a user-specific cache, as this might otherwise randomly affect other users of the same FreshRSS instance. See https://github.com/FreshRSS/FreshRSS/pull/3367#issuecomment-766250249 This should be in another PR though, but must be done before the release of 1.18.0.

2021-03-07 22:27 UTC, Alkarex commented
Patch to avoid SimplePie cache pollution when changing cURL options: https://github.com/FreshRSS/FreshRSS/pull/3502

2021-03-09 19:14 UTC, Alkarex commented
@Jules-Bertholet I have added the user-agent (and proxy) option to the subscription page to add a new feed:
https://github.com/FreshRSS/FreshRSS/pull/3494/commits/f9495f5c97f4386c3c72b99b6e375db6122a9775

![image](https://user-images.githubusercontent.com/1008324/110524701-03528200-8114-11eb-8b63-963b2f8d5efa.png)

Could you please give it a quick test?

2021-03-09 19:37 UTC, Jules-Bertholet commented
@Alkarex Works great! (Proxy not tested)

2021-03-09 19:51 UTC, merged

2021-03-09 19:52 UTC, Frenzie commented
Looks nice :-)

On Tue, Mar 9, 2021 at 8:51 PM Alexandre Alapetite <notifications@github.com>
wrote:

> Merged #3494 <https://github.com/FreshRSS/FreshRSS/pull/3494> into master.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreshRSS/FreshRSS/pull/3494#event-4430955129>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRQBNYUHXY4HMUUIVGHGTTCZ34DANCNFSM4YQSW22Q>
> .
>

2021-03-09 20:06 UTC, Alkarex commented
@Jules-Bertholet Could you please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/master/CREDITS.md ?