Fix various typos and spelling errors in documentation, comments and code.
marienfressinaud/FreshRSS pull request #4134
Opened 2022-01-08 14:55 UTC by thomasrenes

Manually fixed some typos and spelling errors found with [typos](https://github.com/crate-ci/typos). This should improve the documentation and code quality.

Changes proposed in this pull request:

- Fix various typos and spelling errors in documentation, comments and code.

How to test the feature manually:

1. N/A

Pull request checklist:

- [X] clear commit messages
- [ ] code manually tested
- [ ] unit tests written (optional if too hard)
- [ ] documentation updated

[Additional information can be found in the documentation](https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/developers/04_Pull_requests.md).

2022-01-08 15:08 UTC, aledeg requested changes
Thank you for your contribution. Nice work.

Could you rebase your branch to include the latest changes?

2022-01-08 15:08 UTC, aledeg commented on cli/i18n/I18nData.php
> +		$this->synchronizeKeys();
This method has been removed

2022-01-08 15:20 UTC, thomasrenes commented
> Thank you for your contribution. Nice work.
> 
> Could you rebase your branch to include the latest changes?

Thank you! I've rebased this branch.

2022-01-08 15:20 UTC, Alkarex approved these changes

2022-01-08 15:22 UTC, aledeg approved these changes

2022-01-08 15:25 UTC, merged

2022-01-08 15:34 UTC, Alkarex commented
@thomasrenes Thanks, welcome, and please add a line for you in https://github.com/FreshRSS/FreshRSS/blob/edge/CREDITS.md

We could consider adding *typos*  to our CI. See example of `shfmt`, which we are using, and which is also a go package. PR welcome anyone

https://github.com/FreshRSS/FreshRSS/blob/916df412f5b6f7fb9bcfb705a3c8c23e35304410/.github/workflows/tests.yml#L95-L97

2022-01-09 00:13 UTC, Alkarex commented
Continues in https://github.com/FreshRSS/FreshRSS/pull/4138